// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelModelDownload(arg1) {
  return window['go']['main']['App']['CancelModelDownload'](arg1);
}

export function DeleteModel(arg1) {
  return window['go']['main']['App']['DeleteModel'](arg1);
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function ListModelGguFiles(arg1) {
  return window['go']['main']['App']['ListModelGguFiles'](arg1);
}

export function ListModels() {
  return window['go']['main']['App']['ListModels']();
}

export function OpenModelsDir() {
  return window['go']['main']['App']['OpenModelsDir']();
}

export function SearchHuggingFaceModels(arg1) {
  return window['go']['main']['App']['SearchHuggingFaceModels'](arg1);
}

export function StartLlamaServer(arg1) {
  return window['go']['main']['App']['StartLlamaServer'](arg1);
}

export function StartModelDownload(arg1) {
  return window['go']['main']['App']['StartModelDownload'](arg1);
}

export function StopLlamaServer() {
  return window['go']['main']['App']['StopLlamaServer']();
}
