// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelModelDownload(arg1:string):Promise<void>;

export function DeleteModel(arg1:string):Promise<void>;

export function DownloadLlamaServerRelease(arg1:string,arg2:string):Promise<void>;

export function GetLlamaServerInfo():Promise<main.LlamaServerInfo>;

export function GetServerStatus():Promise<main.ServerStatus>;

export function ListLlamaReleaseAssets(arg1:string):Promise<Array<main.LlamaReleaseAsset>>;

export function ListLlamaServerReleases():Promise<Array<main.LlamaServerRelease>>;

export function ListModelGguFiles(arg1:string):Promise<Array<string>>;

export function ListModels():Promise<Array<main.ModelRecord>>;

export function OpenModelsDir():Promise<void>;

export function SearchHuggingFaceModels(arg1:string):Promise<Array<main.HuggingFaceModel>>;

export function StartLlamaServer(arg1:main.ServerConfig):Promise<void>;

export function StartModelDownload(arg1:main.DownloadRequest):Promise<void>;

export function StopLlamaServer():Promise<void>;
