// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListModelGguFiles(arg1) {
  return window['go']['main']['App']['ListModelGguFiles'](arg1);
}

export function SearchHuggingFaceModels(arg1) {
  return window['go']['main']['App']['SearchHuggingFaceModels'](arg1);
}
