// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function ListModelGguFiles(arg1:string):Promise<Array<string>>;

export function SearchHuggingFaceModels(arg1:string):Promise<Array<main.HuggingFaceModel>>;
