// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelModelDownload(arg1) {
  return window['go']['main']['App']['CancelModelDownload'](arg1);
}

export function DeleteLlamaServer() {
  return window['go']['main']['App']['DeleteLlamaServer']();
}

export function DeleteModel(arg1) {
  return window['go']['main']['App']['DeleteModel'](arg1);
}

export function DownloadLlamaServerRelease(arg1, arg2) {
  return window['go']['main']['App']['DownloadLlamaServerRelease'](arg1, arg2);
}

export function GetAppLogs() {
  return window['go']['main']['App']['GetAppLogs']();
}

export function GetLlamaServerDownloadProgress() {
  return window['go']['main']['App']['GetLlamaServerDownloadProgress']();
}

export function GetLlamaServerInfo() {
  return window['go']['main']['App']['GetLlamaServerInfo']();
}

export function GetServerConfig() {
  return window['go']['main']['App']['GetServerConfig']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function HideToTray() {
  return window['go']['main']['App']['HideToTray']();
}

export function ListLlamaReleaseAssets(arg1) {
  return window['go']['main']['App']['ListLlamaReleaseAssets'](arg1);
}

export function ListLlamaServerReleases() {
  return window['go']['main']['App']['ListLlamaServerReleases']();
}

export function ListModelGguFiles(arg1) {
  return window['go']['main']['App']['ListModelGguFiles'](arg1);
}

export function ListModels() {
  return window['go']['main']['App']['ListModels']();
}

export function OpenModelsDir() {
  return window['go']['main']['App']['OpenModelsDir']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SaveServerConfig(arg1) {
  return window['go']['main']['App']['SaveServerConfig'](arg1);
}

export function SearchHuggingFaceModels(arg1) {
  return window['go']['main']['App']['SearchHuggingFaceModels'](arg1);
}

export function ShowMainWindow() {
  return window['go']['main']['App']['ShowMainWindow']();
}

export function StartLlamaServer(arg1) {
  return window['go']['main']['App']['StartLlamaServer'](arg1);
}

export function StartModelDownload(arg1) {
  return window['go']['main']['App']['StartModelDownload'](arg1);
}

export function StopLlamaServer() {
  return window['go']['main']['App']['StopLlamaServer']();
}
